app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("tabsetTest")

app$snapshot()
app$setInputs(navbar = "IDBR and SIC background")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(navbar = "Industry flow analysis")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(navbar = "Regional analysis")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(navbar = "Subject by industry tables")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(navbar = "Industry by subject tables")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
