app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("tabsetTest")

app$snapshot()
app$setInputs(tabs = "IDBR and SIC background")
app$snapshot()
app$setInputs(tabs = "Industry flow analysis")
app$snapshot()
app$setInputs(tabs = "Regional analysis")
app$snapshot()
app$setInputs(tabs = "Subject by industry tables")
app$snapshot()
app$setInputs(tabs = "Industry by subject tables")
app$snapshot()
