app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
shinyTest_sleepTime <- 5.0
app$snapshotInit("tabsetTest")

app$snapshot()
app$setInputs(navbar = "IDBR and SIC background",timeout_=1e+4)
app$snapshot()
app$setInputs(navbar = "industryFlow",timeout_=1e+4)
app$snapshot()
app$setInputs(navbar = "regional",timeout_=1e+4)
app$snapshot()
app$setInputs(navbar = "Subject by industry tables",timeout_=1e+4)
app$snapshot()
app$setInputs(navbar = "Industry by subject tables",timeout_=1e+4)
app$snapshot()
