app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("testTabSubjectbyIndustry")

app$setInputs(navbar = "subjectByIndustry",timeout_=2e+4)
app$snapshot()
app$setInputs(earningsbutton = "Median earnings",timeout_=2e+4)
app$snapshot()
app$setInputs(thresholdinput = "Above",timeout_=2e+4)
app$snapshot()
app$setInputs(thresholdinput = "Below",timeout_=2e+4)
app$snapshot()
app$setInputs(countinput2 = "ethnicity",timeout_=2e+4)
app$snapshot()
app$setInputs(thresholdinput = "All",timeout_=2e+4)
app$snapshot()
app$setInputs(YAGinput2 = "1",timeout_=2e+4)
app$snapshot()
app$setInputs(subjectinput3 = "Sport and exercise sciences",timeout_=2e+4)
app$snapshot()
app$setInputs(earningsbutton = "Proportions",timeout_=2e+4)
app$snapshot()
