app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("testTabIndustrybySubject")

app$setInputs(navbar = "industryBySubject")
app$snapshot()

app$setInputs(earningsbutton2 = "Median earnings",timeout_=1e+4)
app$snapshot()
app$setInputs(countinput3 = "ethnicity",timeout_=1e+4)
app$snapshot()
app$setInputs(YAGinput3 = "10",timeout_=1e+4)
app$snapshot()
app$setInputs(sectionnameinput2 = "PUBLIC ADMINISTRATION AND DEFENCE - COMPULSORY SOCIAL SECURITY",timeout_=1e+4)
app$snapshot()
app$setInputs(YAGinput3 = "1",timeout_=1e+4)
app$snapshot()
app$setInputs(countinput3 = "SECTIONNAME",timeout_=1e+4)
app$setInputs(countinput3 = "FSM",timeout_=1e+4)
app$snapshot()
app$setInputs(earningsbutton2 = "Proportions",timeout_=1e+4)
app$snapshot()
