app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("testTabRegional")

app$setInputs(navbar = "regional",timeout_=2e+4)
app$snapshot()
app$setInputs(regioninput = c("London", "North East", "West Midlands"),timeout_=2e+4)
app$snapshot()
app$setInputs(qualinput2 = "Level 7 (research)",timeout_=2e+4)
app$snapshot()
app$setInputs(sectionnameinput = "TRANSPORTATION AND STORAGE",timeout_=2e+4)
app$snapshot()
app$setInputs(subjectinput2 = "Medicine and dentistry",timeout_=2e+4)
app$snapshot()
app$setInputs(sectionnameinput = "EDUCATION",timeout_=2e+4)
app$setInputs(countinput = "living_in_region",timeout_=2e+4)
app$snapshot()
app$setInputs(YAGinput = "3",timeout_=2e+4)
app$snapshot()
