app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("testTabIndustrybySubject")

app$setInputs(navbar = "industryBySubject")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(earningsbutton2 = "Median earnings")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(countinput3 = "ethnicity")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(countinput3 = "SECTIONNAME")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(earningsbutton2 = "Proportions")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
app$setInputs(YAGinput3 = "1")
Sys.sleep(shinyTest_sleepTime)
app$snapshot()
