app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
shinyTest_sleepTime <- 5.0
app$snapshotInit("testTabIndustryFlowAnalysis")

app$setInputs(navbar = "Industry flow analysis",timeout_=4e+4)
app$snapshot()
app$setInputs(qualinput = "Level 7 (taught)",timeout_=4e+4)
app$snapshot()
app$setInputs(qualinput = "Level 7 (research)",timeout_=4e+4)
app$snapshot()
app$setInputs(qualinput = "Level 8",timeout_=4e+4)
app$snapshot()
app$setInputs(sexinput = "F",timeout_=4e+4)
app$snapshot()
app$setInputs(sexinput = "M",timeout_=4e+4)
app$snapshot()
