app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("testTabIndustryFlowAnalysis")

app$setInputs(navbar = "Industry flow analysis")
app$snapshot()
app$setInputs(qualinput = "Level 7 (taught)")
app$snapshot()
app$setInputs(qualinput = "Level 7 (research)")
app$snapshot()
app$setInputs(qualinput = "Level 8")
app$snapshot()
app$setInputs(sexinput = "F")
app$snapshot()
app$setInputs(sexinput = "M")
app$snapshot()
