app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("testTabs")

app$setInputs(navbar = "industryFlow",timeout_=2.e4)
app$snapshot()
app$setInputs(navbar = "regional",timeout_=2.e4)
app$snapshot()
app$setInputs(navbar = "subjectByIndustry",timeout_=2.e4)
app$snapshot()
app$setInputs(navbar = "industryBySubject",timeout_=2.e4)
app$snapshot()
